apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
- behavior: create
  literals:
  # Use relative URLs - the frontend will call through the same domain via Istio gateway
  - REACT_APP_PRODUCTS_URL_BASE=/api/products/
  - REACT_APP_CART_URL_BASE=/api/cart/
  - REACT_APP_USERS_URL_BASE=/api/users/
  - REACT_APP_SEARCH_URL_BASE=/api/search/
  name: store-ui-configmap
generatorOptions:
  disableNameSuffixHash: true