apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-deployment
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name: users
        image: users:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: users-configmap
              key: MONGO_URI
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: users-configmap
              key: DATABASE
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP