apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cart
  - products
  - search
  - store-ui
  - users

# Base ConfigMap that will be merged with overlays
configMapGenerator:
  - name: app-env
    literals:
      - ENVIRONMENT=base