apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  selector:
    matchLabels:
      app: cart-deployment
  template:
    metadata:
      labels:
        app: cart-deployment
      annotations:
        sidecar.istio.io/proxyCPU: "0"
        sidecar.istio.io/proxyCPULimit: "0"
        sidecar.istio.io/proxyMemory: "0"
        sidecar.istio.io/proxyMemoryLimit: "0"
    spec:
      containers:
      - name: cart
        image: cart:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 7000
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: "7000"
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: cart-configmap
              key: SPRING_REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: cart-configmap
              key: SPRING_REDIS_PORT
        - name: SPRING_REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cart-configmap
              key: SPRING_REDIS_PASSWORD
        - name: APP_ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL_ROOT
          value: "WARN"
        - name: LOG_LEVEL_APP
          value: "INFO"
        - name: MANAGEMENT_HEALTH_SHOW_DETAILS
          value: "never"