apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: NAMESPACE_PLACEHOLDER

resources:
- ../../../base/store-ui
- service-nodeport.yaml

images:
- name: store-ui:latest
  newName: image.registry.local:5001/store-ui
  newTag: latest

patches:
- path: deployment-patch.yaml
