apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: NAMESPACE_PLACEHOLDER

resources:
- ../../../base/store-ui
- service-nodeport.yaml

images:
- name: store-ui:latest
  newName: image.registry.local:5001/store-ui
  newTag: latest

configMapGenerator:
- behavior: create
  literals:
  # Use Kubernetes service URLs for in-cluster communication
  - REACT_APP_PRODUCTS_URL_BASE=http://localhost:8081/
  - REACT_APP_CART_URL_BASE=http://localhost:8080/
  name: store-ui-configmap
generatorOptions:
  disableNameSuffixHash: true
patches:
- path: deployment-patch.yaml
