apiVersion: v1
kind: Service
metadata:
  name: store-ui-service-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30084
  selector:
    app: store-ui-deployment
    