apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  template:
    spec:
      containers:
      - name: users
        image: image.registry.local:5001/users:latest
        imagePullPolicy: Always
