apiVersion: v1
kind: Service
metadata:
  name: users-service-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30083
  selector:
    app: users-deployment
