apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  template:
    spec:
      containers:
      - name: products
        image: image.registry.local:5001/products:latest
