apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
resources:
- ../../../base/products
- service-nodeport.yaml

images:
- name: products:latest
  newName: image.registry.local:5001/products
  newTag: latest

patches:
- path: deployment-patch.yaml
