apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30081
  selector:
    app: products-deployment
