apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  template:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: "ELASTICSEARCH_HOSTS"
          value: "http://elasticsearch-service:9200"
        - name: "ELASTICSEARCH_USERNAME"
          value: "elastic"
        - name: "ELASTICSEARCH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: elastic-password