version: v2beta1
name: search

imports:
  - path: "../.devpilot-scripts/devspace-pipelines.yaml"

vars:
  SERVICE_NAME: "search"
  K8S_MANIFEST_PATH_LOCAL: "${K8S_DIR}/infra/k8s/apps/overlays/local/search/"
  K8S_MANIFEST_PATH_AZURE: "${K8S_DIR}/infra/k8s/apps/overlays/azure/search/"

pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      start_dev search
  # Custom pipeline to run the debug server. You can run this pipeline via `devspace run-pipeline debug-server`
  debug-server:
    run: |-
      echo "Running products debug server."
      start_dev search-debug

dev:
  search:
    labelSelector:
      app: search-deployment
    container: search
    devImage: "image.registry.local:5001/search:dev"
    sync:
      - path: ./:/app
        excludePaths:
          - .devspace/
          - node_modules/
          - .git/
          - "*.log"
        initialSync: preferLocal
        printLogs: true
    terminal:
      command: ./devspace_start.sh
    ports:
      - port: "4000:4000"
      - port: "9230:9230"
    open:
      - url: http://localhost:4000/api/docs
    env:
      - name: NODE_ENV
        value: "development"
      - name: ELASTIC_URL
        value: "http://localhost:9200/"
  # Remote Debug configuration for the search service
  search-debug:
    labelSelector:
      app: search-deployment
    container: search
    command:
      - npm
      - run
      - debug
    ports:
      - port: "4000:4000"
      - port: "9230:9230"
