apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce

resources:
  - ../../../base/cart

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: cart-configmap
    behavior: create
    literals: 
    - SPRING_REDIS_HOST=redis-service.shared-services.svc.cluster.local
    - SPRING_REDIS_PORT=6379
    - SPRING_REDIS_PASSWORD=
generatorOptions:
  disableNameSuffixHash: true # use a static name