apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: NAMESPACE_PLACEHOLDER
resources:
- ../../../base/cart
- service-nodeport.yaml

images:
- name: cart:latest
  newName: image.registry.local:5001/cart
  newTag: latest

patches:
- path: deployment-patch.yaml