apiVersion: v1
kind: Service
metadata:
  name: cart-service-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 7000
    nodePort: 30080
  selector:
    app: cart-deployment
