apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: cart-deployment
