apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
spec:
  selector:
    matchLabels:
      app: es-deployment
  template:
    metadata:
      labels:
        app: es-deployment
    spec:
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-pvc
      containers:
      - name: es
        image: elasticsearch:7.17.9
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        - name: bootstrap.memory_lock
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms128m -Xmx128m"
        - name: node.store.allow_mmap
          value: "false"
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "false"
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
