apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi