apiVersion: v1
kind: Service
metadata:
  name: es-service-nodeport
spec:
  type: NodePort
  ports:
  - name: es-http
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 32200
  - name: es-transport
    protocol: TCP
    port: 9300
    targetPort: 9300
    nodePort: 32300
  selector:
    app: es-deployment

