apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  selector:
    matchLabels:
      app: products-deployment
  template:
    metadata:
      labels:
        app: products-deployment
      annotations:
        sidecar.istio.io/proxyCPU: "0"
        sidecar.istio.io/proxyCPULimit: "0"
        sidecar.istio.io/proxyMemory: "0"
        sidecar.istio.io/proxyMemoryLimit: "0"
    spec:
      containers:
      - name: products
        image: products:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_URI  ## Define the name of the variable
          valueFrom:
            configMapKeyRef:
              name: products-configmap   ## This must match the name of the configmap
              key: MONGO_URI  ## The key to fetch
        - name: DATABASE  ## Define the name of the variable
          valueFrom:
            configMapKeyRef:
              name: products-configmap   ## This must match the name of the configmap
              key: DATABASE  ## The key to fetch
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP