apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: NAMESPACE_PLACEHOLDER
resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
- behavior: create
  literals:
  - MONGO_URI=mongodb://mongo-root-username:mongo-root-password@mongo-service.shared-services.svc.cluster.local:27017/
  - DATABASE=NAMESPACE_PLACEHOLDER
  name: products-configmap
generatorOptions:
  disableNameSuffixHash: true