apiVersion: v1
kind: Service
metadata:
  name: mongo-service-nodeport
namespace: shared-services
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32017
  selector:
    app: mongo-deployment
