apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
- behavior: create
  literals:
  - ELASTIC_URL=http://elastic-service.shared-services.svc.cluster.local:9200/
  name: search-configmap
generatorOptions:
  disableNameSuffixHash: true