apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
resources:
- ../../../base/search
- service-nodeport.yaml

images:
- name: search:latest
  newName: image.registry.local:5001/search
  newTag: latest

patches:
- path: deployment-patch.yaml
