apiVersion: v1
kind: Service
metadata:
  name: search-service-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30082
  selector:
    app: search-deployment
