apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce

resources:
- ../../../base/store-ui
- store-ui-gateway.yaml
- store-ui-vs.yaml

images:
- name: store-ui:latest
  newName: kubecondemo.azurecr.io/store-ui
  newTag: latest

configMapGenerator:
- behavior: create
  literals:
  # Use Kubernetes service URLs for in-cluster communication
  - REACT_APP_PRODUCTS_URL_BASE=http://products-service:5000/
  - REACT_APP_CART_URL_BASE=http://cart-service:7000/
  - REACT_APP_SEARCH_URL_BASE=http://search-service:4000/
  - REACT_APP_USERS_URL_BASE=http://users-service:9090/
  name: store-ui-configmap
generatorOptions:
  disableNameSuffixHash: true