apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: NAMESPACE_PLACEHOLDER

resources:
- ../../../base/store-ui
- store-ui-gateway.yaml
- store-ui-vs.yaml

images:
- name: store-ui:latest
  newName: kubecon.azurecr.io/store-ui
  newTag: latest